fkie-cad/dewolf

- .github/issue-branch.yml
- .github/workflows/create-issue-branch.yml
I created an action to include the following App:
https://github.com/robvanderleek/create-issue-branch
This way, we can create a branch for a given issue by commenting `/cib` or `/create-issue-branch`.
I configured the app to:
* not only create a branch but also a (draft) PR
* copy description, labels, assign and milestone from the given issue to the newly created PR
* auto close the original issue once the branch is merged
> Integrate GitHub Action to automatically create branches

- decompiler/pipeline/controlflowanalysis/expression_simplification.py
- decompiler/pipeline/dataflowanalysis/deadcodeelimination.py
- decompiler/pipeline/dataflowanalysis/identity_elimination.py
- tests/pipeline/controlflowanalysis/test_expression_simplification.py
- tests/test_sample_binaries.py
Handles the issue raised in #16 
Also refactored `expression_simplification.py` while I was at it.
> Simplify dereference operations containing address-of operations

- Makefile.venv
Closes #65
I notice that `install_api.py` isn't bundled. Should we actually update to use `$BINARY_NINJA_PATH/scripts/install_api.py` instead of `./install_api.py` by default?
> Makefile: add environment variable to specify Binary Ninja path

- requirements.txt
There is a bug in the current networkx version. So we want to exclude it.
> Exclude networkz version 2.8.4

- decompiler/frontend/binaryninja/handlers/constants.py
Currently, all strings a represented as extern constants. But, we do not want this because this reduces the readability.
> Fix all strings extern constants

- decompiler/util/decoration.py
- tests/util/test_decoration.py
When plotting an AST, the case node contains a string containing a ':'. Then, the string must be of the form '"... : ..."' when using pydot. 
Update decoration such that the tests pass again.
> Networkx pytdot

- decompiler/util/widget.py
Remove font update on every interaction. Only invoke one worker when using `follow` in the GUI
> 118 gui decompilation gets started multiple times

- decompiler/pipeline/controlflowanalysis/restructuring_commons/ast_processor.py
- decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/initial_switch_node_constructer.py
- decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/missing_case_finder_sequence.py
- decompiler/structures/ast/ast_nodes.py
- tests/pipeline/controlflowanalysis/restructuring_commons/test_condition_aware_refinement.py
Handle redundant conditions for conditions-nodes in front of sequence nodes, as in the following example:
Here the condition of node 4 is irrelevant for the condition of node 8
> Redundant conditions

- decompiler/backend/cexpressiongenerator.py
- decompiler/backend/codevisitor.py
- decompiler/pipeline/controlflowanalysis/expression_simplification.py
- decompiler/pipeline/controlflowanalysis/variable_name_generation.py
- decompiler/pipeline/dataflowanalysis/type_propagation.py
- decompiler/structures/pseudo/typing.py
Currently, `typing/Float` extends `typing/Integer`. This makes it non trivial to check if a type is an integer.
eg: `isInstance(type, Integer) and not isInstance(type, Float)` or `type.__class__ == Integer.__class__`
This pull request is a quick fix which changes the super type of `Float` from `Integer` to `Type` and all affected code by this change.
> Change super type of typing/Float from typing/Integer to typing/Type

- decompiler/pipeline/controlflowanalysis/readability_based_refinement.py
- tests/pipeline/controlflowanalysis/test_readability_based_refinement.py
This fix prevents the `ForLoopVariableRenamer` from generating wrong For Loop declarations.
E.g. this code (where `b` is e.g. an argument or defined earlier)
```
b = foo(b);
while(b <= 5){
...  
b = b + 1
}
```
will no longer be changed to
```
for(i = foo(i); i <= 5; i = i + 1)
...
}
```
Instead, the correct for loop declaration `i = foo(b)` will be created.
> fix self referential declarations in For Loops

- decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/missing_case_finder_intersecting_constants.py
- decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/missing_case_finder_sequence.py
- tests/pipeline/controlflowanalysis/test_pattern_independent_restructuring_blackbox.py
We have two minor bugs for adding the default case, by not checking that the default-condition can be None, if we can not transform it back into symbols. 
The other is in inserting intersecting cases, where the insertion before has a bug.
> [Bug] Fix bug in default-case and start with insert intersecting cases

- decompiler/structures/pseudo/typing.py
This pr removes the duplicated `FunctionTypeDef` class definition introduced with #253.
> Remove duplicated 'FunctionTypeDef' definition

- decompiler/pipeline/controlflowanalysis/readability_based_refinement.py
- decompiler/util/default.json
- tests/pipeline/controlflowanalysis/test_readability_based_refinement.py
For the ISR cooperation, we promised a config-option that turns the reconstruction of for-loops on and off.
This is now implemented. If the option is set to `true`, still all other configuration options have to hold in order to reconstruct a for-loop. If it is set to `false`, no for loop is restructured.
Question: This overwrites the option `force_for_loop`, i.e., if `restructure_for_loop` is set to `false` and `force_for_loop` to `true`, no for-loop is restructured. Do we want a warning in this scenario?
> Add configuration option for allowing for-loops

- decompiler/pipeline/dataflowanalysis/dead_loop_elimination.py
- decompiler/structures/graphs/cfg.py
This commit removes the wildcard import `from .branches import *` and replaces it with explicit imports.
Reasons to do so:
- The wildcard import unnecessarily pollutes the namespace of `cfg` with all of `branch`es imports.
- The aforementioned pollution caused typecheckers and linters to partially fail because of weird side effects.
- "Explicit is better than implicit"  (The Zen of Python)
> [Code Quality] Remove wildcard import

- decompiler/pipeline/dataflowanalysis/common_subexpression_elimination.py
- pytest.ini
- requirements.txt
- tests/conftest.py
Currently common subexpression elimination uses lists to store which instructions use a specific expression. This PR replaces this usage with pythons `Counter` class to improve asymptotic runtime.
Additionally this pr adds parallelization to tests using [pytest-xdist](https://pypi.org/project/pytest-xdist/).
> Improve performance of common subexpression elimination and parallel testing

- decompiler/pipeline/commons/expressionpropagationcommons.py
- decompiler/pipeline/dataflowanalysis/expressionpropagationmemory.py
- decompiler/util/iteration_util.py
- tests/pipeline/dataflowanalysis/test_expression_propagation.py
In some cases the decompiler fails to reconstruct simple control structures, because the decompiled code contains redundant variables. These variables are caused by Phi functions, that use the same value indifferent to the control flow path taken.
This PR adds code that removes these redundant Phi functions before each expression propagation iteration, enabling more expressions to be propagated.
An example where this causes a switch to not be constructed is `test17` in [systemtest/32/3/test_condition](https://github.com/fkie-cad/dewolf/files/14208002/test_condition.zip).
> Improve expression propagation by removing redundant Phi functions

- .github/workflows/release.yml
- plugin.json
- update_for_release.py
#392 doesn't work with the branch protection rules of the repository. The github action tries to push a commit to `main`, which gets rejected. 
This PR fixes this by changing the automatic release action to not push the newly created commit to main. Instead, the commit is simply tagged and only the tag is pushed. This means that the release commit is not contained in the main branch, which I think is fine though.
> Change automatic release to not push to main

- decompiler/frontend/binaryninja/handlers/symbols.py
Binary Ninja 4.0 introduced `SymbolType.SymbolicFunctionSymbol`, which is now used by the frontend.
This change prevents dewolf from crashing when Binary Ninja 3.5 is used.
> Fix support for Binary Ninja 3.5 by not requiring SymbolicFunctionSymbol

- decompiler/pipeline/controlflowanalysis/variable_name_generation.py
- decompiler/util/default.json
- tests/pipeline/controlflowanalysis/test_variable_name_generation.py
> Revive: Fix Hungarian Notation

- decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/missing_case_finder_condition.py
- decompiler/pipeline/controlflowanalysis/restructuring_commons/condition_aware_refinement_commons/switch_extractor.py
- decompiler/structures/ast/syntaxforest.py
- tests/pipeline/controlflowanalysis/test_pattern_independent_restructuring_blackbox.py
First, the switch-extractor did not consider sequence nodes with a non-trivial reaching-condition. Therefore, we did not extract some switches leading to fewer cases or not the ability to merge cases.
Second, there was a minor bug, because we extracted switches from conditions nodes even if they were children of a sequence node with a non-trivial reaching-condition.
> SwitchExtractor Improvement

- decompiler/pipeline/controlflowanalysis/expression_simplification/rules/collapse_nested_constants.py
This PR relaxes the check for constants to be equal, by only checking that the size of their types matches. This will allow nested expressions with mixed types, like pointer + integer to be simplified.
> [Expression Simplifcation] Relax checks in CollapseNestedConstants to allow more simplifcations

- decompiler/backend/cexpressiongenerator.py
- decompiler/backend/codevisitor.py
This PR fixes some cases where string literals were not properly escaped.
> Fix escaping of string literals

- decompiler/structures/graphs/basicblock.py
- decompiler/structures/graphs/restructuring_graph/transition_cfg.py
- tests/structures/graphs/test_basicblock.py
For some larger binaries, expression propagation can be quite slow.
One of the many reasons for this is that networkx assumes (maybe rightfully so), that calls to `__str__` of nodes are relatively cheap, compared operation of calculating if a path exists between two nodes.
However, because basicblocks create a string representation by printing every single instruction, a lot of time is spend on this instead.
This PR changes changes the implementation of `__str__` of basicblocks to simply use the cheap debu representation instead.
> Improve performance of expression propagation

- decompiler/pipeline/preprocessing/phi_predecessors.py
Improve performance of the PhiFunctionFixer pipeline stage by not recomputing basic block definition lookup each time.
> Improve PhiFunctionFixer performance

- decompiler/frontend/binaryninja/frontend.py
- decompiler/frontend/binaryninja/tagging.py
Currently when decompiling a single function, compiler idioms will dissemble the whole binary, which takes a considerable amount of time, when the goal is to only decompile a single function with a couple of instructions.
This PR fixes this by ~instead directly taking the disassembly from binaryninja an passing it to the compiler idioms tagging~ only disassembling the file once, the same way binary ninja only loads the binary once even when decompiling multiple functions.
> Improve compiler idioms performance

- decompiler/backend/codegenerator.py
- decompiler/frontend/binaryninja/frontend.py
- decompiler/pipeline/pipeline.py
- decompiler/pipeline/preprocessing/missing_definitions.py
- decompiler/task.py
- tests/test_sample_binaries.py
Currently, the pipeline considers the output string to check whether a test crashes. But these strings are different.
> Fix Pipeline
